In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.remoteok.com/remote-dev-jobs'
headers = {'User-Agent': 'Mozilla/5.0 (windows NT 10.0; Win64; x64)'}

response = requests.get(url, headers = headers)
soup = BeautifulSoup(response.text, 'html.parser')


job_list = []

for job in soup.select('tr.job'):
    title = job.select_one('h2')
    company = job.select_one('h3')
    tags = [tag.get_text(strip=True) for tag in job.select('span.tag')]
    
    
    
    if title and company:
        job_list.append(
            {'title': title.get_text(strip=True),
             'company': company.get_text(strip=True),
             'skills': tags}
        )

df = pd.DataFrame(job_list)

df

Empty DataFrame
Columns: []
Index: []

In [ ]:
import requests
import pandas as pd

url = 'https://www.remoteok.com/remote-dev-jobs.json'
headers = {'User-Agent': 'Mozilla/5.0', 'Accept' : 'application/json'}

response = requests.get(url, headers = headers)
jobs = response.json()


jobber = []
for job in jobs[1:]:
    jobber.append({
        'title' : job.get('position'),
        'company' : job.get('company'),
        'skills' : job.get('tags'),
        'link' : job.get('url')
    })



Lf = pd.DataFrame(jobber)
Lf

,title,company,skills,link
0,Senior UX UI designer,GoMining,"[ui, ux, design, designer, support, developer,...",https://remoteOK.com/remote-jobs/remote-senior...
1,Senior Backend Engineer HyperDX,ClickHouse,"[developer, cloud, senior, engineer, backend, ...",https://remoteOK.com/remote-jobs/remote-senior...
2,Intermediate Full Stack Engineer,Runn,"[technical, engineer, dev, full time, saas, we...",https://remoteOK.com/remote-jobs/remote-interm...
3,Senior Full Stack Engineer,Runn,"[technical, engineer, senior, dev, full time, ...",https://remoteOK.com/remote-jobs/remote-senior...
4,WordPress Developer,Data Group,[dev],https://remoteOK.com/remote-jobs/remote-wordpr...
...,...,...,...,...
88,Hardware Infrastructure Site Reliability Engineer,SpaceX,"[system, developer, software, reliability, eng...",https://remoteOK.com/remote-jobs/remote-hardwa...
89,Mid Market Account Manager,Cypress.io,"[manager, technical, support, developer, softw...",https://remoteOK.com/remote-jobs/remote-mid-ma...
90,Software Engineer Sandboxing,Anthropic,"[software, system, developer, code, engineer, ...",https://remoteOK.com/remote-jobs/remote-softwa...
91,Site Reliability Engineer,Point72,"[design, system, security, python, support, de...",https://remoteOK.com/remote-jobs/remote-site-r...
92,Senior Software Engineer,Chainguard,"[software, design, developer, senior, engineer...",https://remoteOK.com/remote-jobs/remote-senior...